<<<<<<< HEAD
[[redirects]]
    from = "/*"
    to = "/index.html"
=======
[[redirects]]
    from = "/*"
    to = "/index.html"
>>>>>>> b3c90324104bd431aea145a0213812a7e4d95e3a
    status = 200
[[redirects]]
  from = "/MERN_Abid_Hussain_Resume.pdf"
  to = "/MERN_Abid_Hussain_Resume.pdf"
  status = 200
  force = true
